services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=park_house'
      - 'POSTGRES_USER=park_admin'
      - 'POSTGRES_PASSWORD=no_secrets_among_devs'
    ports:
      - '6432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres_keycloak:
    image: 'postgres:17-alpine'
    container_name: postgres_keycloak
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_USER=keycloak'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
    ports:
      - "9080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

    depends_on:
      - postgres_keycloak

volumes:
  postgres-data:
  postgres-keycloak-data: