name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres-test:
        image: 'postgres:17-alpine'
        env:
          POSTGRES_DB: test_park_house
          POSTGRES_USER: test_park_admin
          POSTGRES_PASSWORD: no_secrets_among_devs
        ports:
          - '7432:5432'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: SPRING_PROFILES_ACTIVE=test mvn test
